### PR TITLE
feat: allow domain,scheme,port to be configured

### LINKED ISSUE #42: Allow setting fauna endpoint
There doesn't seem to be an option to set the fauna endpoint when using the extension. During development it could be useful to set the fauna endpoint to `http://localhost:8443` when working with the docker image.

### PR DESCRIPTION
**Pull request by aleclarson**
Closes #42 
Depends on #51 (merge that first)

The relevant commit: https://github.com/fauna/vscode/pull/52/commits/6ebde387e0dbd9bfd732bfcdd10f5578498cf546

### Description
Add ability to configure domain,shceme,port
Bonus: The extension reloads itself when its configuration is changed.

### Example
Via vs code settings
```
- `fauna.domain`: The hostname of an endpoint’s Fauna instance
- `fauna.scheme`: One of https or http
- `fauna.port`: The UNIX port number of endpoint’s Fauna instance
```
Via config file `.faunarc`
```
FAUNA_DOMAIN=db.fauna.com
FAUNA_SCHEME=https
FAUNA_PORT=443
```

### CODE REVIEW

**Comment by SubZtep** [comment]
Is there any plan to merge this PR? It would make this extension very useful, better than local GraphiQL.

**Comment by fireridlle** [comment]
Hi @aleclarson. Thank you for contributing and sorry that we missed this PR. PR has conflicts with the master branch. I will resolve them as they mostly related to rebranding.

Just a question, why baseUrl was decided as config property and not domain, shema, port? All our drivers, as well as shell, support these params and I would like to keep this consistency for vscode too.

**Comment by aleclarson** [comment]
> Just a question, why baseUrl was decided as config property and not domain, shema, port?

Better DX. There's no potential to forget to change the default scheme from `https` to `http` etc. Just one straight-forward setting.

**Comment by fireridlle** [comment]
@aleclarson here is the list of changes
- conflicts resolved
- split base url to domain, scheme, port
- fix register tree provider on config change. if config changed when sidebar with tree provided visibly, it causes an error (because dispose() delete this tree)

**Review by parkhomenko — APPROVED** [review]

**Pull request merged**
